// Build script: merges content.js + ui.js + game.js into js/bundle.js.
// One file = no mixed-version module loads from CDN caches, ever.
// Usage: node tools/build.mjs
import fs from 'fs';
import path from 'path';
import {fileURLToPath} from 'url';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));

const FILES=['js/content.js','js/ui.js','js/game.js'];
function strip(src){
  return src
    .replace(/^import[\s\S]*?from\s*['"][^'"]+['"];[ \t]*$/gm, '')  // imports (incl. multi-line)
    .replace(/^export \{[^}]*\};?[ \t]*$/gm, '')                    // export lists
    .replace(/^export (const|let|function|class)/gm, '$1');
}
const seen=new Map();
let out="/* ROBOTIQUE 3D — single-file bundle (generated by tools/build.mjs; edit js/*.js sources) */\n"+
        "import * as THREE from 'three';\n";
for(const f of FILES){
  const stripped=strip(fs.readFileSync(path.join(root,f),'utf8'));
  // guard: duplicate top-level declarations across modules would silently shadow
  for(const m of stripped.matchAll(/^(?:const|let|function|class)\s+([A-Za-z_$][\w$]*)/gm)){
    if(seen.has(m[1])) throw new Error('duplicate top-level name "'+m[1]+'" in '+f+' (also in '+seen.get(m[1])+')');
    seen.set(m[1], f);
  }
  out+='\n/* ===================== '+f+' ===================== */\n'+stripped;
}
out+='\n';
fs.writeFileSync(path.join(root,'js/bundle.js'), out);
console.log('built js/bundle.js —', out.length, 'bytes,', seen.size, 'top-level names, no duplicates');
